name = "price-update"
account_id = "###"
compatibility_flags = []
workers_dev = false
compatibility_date = "2023-08-24"
kv_namespaces = [
  { binding = "peercoin_kv", id = "###", preview_id = "###" }
]

[triggers]
crons = ["0 * * * *"]