name = "price-update"
type = "javascript"

account_id = "###"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [ 
  { binding = "###", id = "###", preview_id="###" }
]

[triggers]
crons = ["*/30 * * * *"]

[vars]
CURRCONV_KEY = ###