name = "price-update"

account_id = "###"
workers_dev = true
compatibility_date = "2021-12-01"

kv_namespaces = [ 
  { binding = "###", id = "###", preview_id="###" }
]

[triggers]
crons = ["0 * * * *"]

[vars]
CURRCONV_KEY = ###
PAPRIKA_TOKEN = ###